name: CI

on: [push]

env:
  DEPLOY_PATH: ${{ secrets.PROJECT_PATH }}
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Устанавливаем env
      - name: Install env
        run: echo "VUE_APP_API_URL="${{ secrets.API_URL }} > .env.production
      # Собираем приложение
      - name: Build Appliction
        run: $BUILD_SCRIPT
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: /${{ env.DEPLOY_PATH }}
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at hosting/"
#name: Deploy
#on: [push]
#env:
#  DEPLOY_PATH: /secrets.PROJECT_PATH
#  BUILD_SCRIPT: npm run build
#  BUILD_SCRIPT_OUTPUT: dist
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Copy repository contents via scp
#
#        uses: appleboy/scp-action@master
#        env:
#          HOST: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSHKEY }}
#        with:
#          source: "."
#          target: "/var/deployment/lib-vue"
#
#      - name: Executing remote command
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          USERNAME: ${{ secrets.USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSHKEY }}
#          #script: cd /var/deployment/lib-vue && chmod 744 ./deploy.sh && ./deploy.sh
#          script: cd /var/deployment/lib-vue && npm install && npm run build && rm -rf /${{ secrets.PROJECT_PATH }}/* && cp -r /var/deployment/lib-vue/dist/. /${{ secrets.PROJECT_PATH }}/